// Generated by CoffeeScript 1.6.3
(function() {
  var base, connect, ecstatic, http, mw, net, netServer, path, server, shoe, sock;

  ecstatic = require('ecstatic');

  connect = require('connect');

  http = require('http');

  path = require('path');

  shoe = require('shoe');

  base = require('../shared/base');

  net = require('net');

  mw = connect();

  sock = shoe();

  mw.use(ecstatic({
    root: path.join(__dirname, '../../public')
  }));

  sock.on('connection', function(stream) {
    return stream.pipe(base.createStream()).pipe(stream);
  });

  server = http.createServer(mw);

  sock.install(server, '/stream.shoe');

  server.listen(3000, function() {
    return console.log("app is listening on localhost:" + (server.address().port));
  });

  netServer = net.createServer(function(stream) {
    stream.on('error', function(err) {
      return console.log('error: ', err);
    });
    return stream.pipe(base.createStream()).pipe(stream);
  });

  netServer.listen(3010, function() {
    return console.log("net is listening on localhost:" + (netServer.address().port));
  });

}).call(this);
