// Generated by CoffeeScript 1.6.3
(function() {
  var base, connect, ecstatic, http, mw, path, server, shoe, sock;

  ecstatic = require('ecstatic');

  connect = require('connect');

  http = require('http');

  path = require('path');

  shoe = require('shoe');

  base = require('../shared/base');

  mw = connect();

  sock = shoe();

  mw.use(ecstatic({
    root: path.join(__dirname, '../../public')
  }));

  sock.on('connection', function(stream) {
    return stream.pipe(base.createStream()).pipe(stream);
  });

  server = http.createServer(mw);

  sock.install(server, '/stream.shoe');

  server.listen(3001, function() {
    return console.log('app is listening on localhost:3000');
  });

}).call(this);
