// Generated by CoffeeScript 1.6.3
(function() {
  var base, binders, domready, ldata, reconnect, username;

  require('shoe');

  reconnect = require('reconnect');

  domready = require('domready');

  binders = require('../client/live-binders');

  ldata = require('live-data');

  base = require('../shared/base');

  window.val = base.val;

  window.app = base.app;

  window.m = base.messages;

  window.ldata = ldata;

  username = new ldata.Value('No One');

  domready(function() {
    var input, label, message, messagesBinding, name, usernameField;
    messagesBinding = null;
    (function() {
      var container;
      container = document.createElement('div');
      document.body.appendChild(container);
      container.style.overflow = 'scroll';
      container.style.position = 'relative';
      container.style.height = '500px';
      container.style.border = '1px solid black';
      container.id = 'messages';
      messagesBinding = binders.array(container, function(val) {
        var el;
        el = document.createElement('div');
        val.map(function(str) {
          return str.replace(/\t/g, '    ').replace(/[ ]/g, '&nbsp;');
        }).pipe(binders.innerHTML(el));
        return el;
      });
      base.messages.pipe(messagesBinding);
      container.scrollTop = container.scrollHeight;
      return setInterval(function() {
        if (container.scrollHeight - container.scrollTop <= 505) {
          return container.scrollTop = container.scrollHeight;
        }
      }, 10);
    })();
    usernameField = document.createElement('input');
    username.pipe(binders.value(usernameField)).pipe(username);
    document.body.appendChild(usernameField);
    (function() {
      var clear, form, msg;
      form = document.createElement('form');
      form.addEventListener('submit', function(e) {
        var sendingMessage;
        e.stopPropagation();
        e.preventDefault();
        e.returnValue = false;
        sendingMessage = msg.value;
        base.messages.push(username.map(function(username) {
          return "" + username + ": " + sendingMessage;
        }));
        msg.value = '';
        return false;
      });
      document.body.appendChild(form);
      form.style.display = 'inline';
      msg = document.createElement('input');
      form.appendChild(msg);
      clear = document.createElement('button');
      clear.textContent = 'Clear Chat';
      clear.addEventListener('click', function(e) {
        return messagesBinding.each(function() {
          return this.pop();
        });
      });
      return document.body.appendChild(clear);
    })();
    label = document.createElement('div');
    document.body.appendChild(label);
    base.val.pipe(binders.innerHTML(label));
    input = document.createElement('input');
    document.body.appendChild(input);
    base.val.pipe(binders.value(input)).pipe(base.val);
    name = document.createElement('input');
    document.body.appendChild(name);
    base.name.pipe(binders.value(name)).pipe(base.name);
    message = document.createElement('span');
    document.body.appendChild(message);
    return base.message.pipe(binders.textContent(message));
  });

  reconnect(function(stream) {
    return stream.pipe(base.createStream()).pipe(stream);
  }).connect('/stream.shoe');

}).call(this);
