// Generated by CoffeeScript 1.6.3
(function() {
  var base, binders, domready, ldata, reconnect;

  require('shoe');

  reconnect = require('reconnect');

  domready = require('domready');

  binders = require('../client/live-binders');

  ldata = require('../shared/live-data');

  base = require('../shared/base');

  window.val = base.val;

  window.app = base.app;

  window.ldata = require('../shared/live-data');

  domready(function() {
    var input, label, message, messages, name;
    messages = null;
    (function() {
      var container, messagesBinding;
      container = document.createElement('div');
      document.body.appendChild(container);
      container.style.overflow = 'scroll';
      container.style.position = 'relative';
      container.style.height = '500px';
      container.style.border = '1px solid black';
      messagesBinding = binders.array(container, function(val) {
        var el;
        el = document.createElement('div');
        val.pipe(binders.textContent(el));
        return el;
      });
      base.messages.pipe(messagesBinding);
      container.scrollTop = container.scrollHeight;
      return setInterval(function() {
        if (container.scrollHeight - container.scrollTop < 505) {
          return container.scrollTop = container.scrollHeight;
        }
      }, 10);
    })();
    (function() {
      var clear, form, msg;
      form = document.createElement('form');
      form.addEventListener('submit', function(e) {
        e.stopPropagation();
        e.preventDefault();
        e.returnValue = false;
        base.messages.push(new ldata.Value(msg.value));
        msg.value = '';
        return false;
      });
      document.body.appendChild(form);
      form.style.display = 'inline';
      msg = document.createElement('input');
      form.appendChild(msg);
      clear = document.createElement('button');
      clear.textContent = 'Clear Chat';
      clear.addEventListener('click', function(e) {
        return base.messages.each(function() {
          return base.messages.pop();
        });
      });
      return document.body.appendChild(clear);
    })();
    label = document.createElement('div');
    document.body.appendChild(label);
    base.val.pipe(binders.innerHTML(label));
    input = document.createElement('input');
    document.body.appendChild(input);
    base.val.pipe(binders.value(input)).pipe(base.val);
    name = document.createElement('input');
    document.body.appendChild(name);
    base.name.pipe(binders.value(name)).pipe(base.name);
    message = document.createElement('span');
    document.body.appendChild(message);
    return base.message.pipe(binders.textContent(message));
  });

  reconnect(function(stream) {
    return stream.pipe(base.createStream()).pipe(stream);
  }).connect('/stream.shoe');

}).call(this);
