// Generated by CoffeeScript 1.6.3
(function() {
  var ldata;

  ldata = require('live-data');

  exports.textContent = function(el) {
    var val;
    val = new ldata.Value;
    val.on('update', function(d) {
      return el.textContent = d;
    });
    return val;
  };

  exports.innerHTML = function(el) {
    var val;
    val = new ldata.Value;
    val.on('update', function(d) {
      return el.innerHTML = d;
    });
    return val;
  };

  exports.value = function(el) {
    var applyDom, applyModel, val;
    val = new ldata.Value;
    applyDom = function(d) {
      if (typeof d === 'string' && d.length > 0 && el.value !== d) {
        return el.value = d;
      }
    };
    val.on('update', applyDom);
    if (el.value) {
      val.set(el.value);
    }
    applyModel = function() {
      return val.set(el.value);
    };
    el.addEventListener('input', applyModel);
    el.addEventListener('keyup', applyModel);
    return val;
  };

  exports.array = function(parent, fn) {
    var arr, elements;
    arr = new ldata.Array;
    elements = {};
    arr.on('insert', function(index, val, key, sbKey) {
      var el;
      el = elements[key] = fn(val);
      parent.appendChild(el);
      return arr.emit('dom:insert', index, el, val, key, sbKey);
    });
    arr.on('remove', function(index, val, key) {
      parent.removeChild(elements[key]);
      return delete elements[key];
    });
    return arr;
  };

}).call(this);
