// Generated by CoffeeScript 1.6.3
(function() {
  var App, EventEmitter, muxy,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  muxy = require('muxy');

  module.exports = App = (function(_super) {
    __extends(App, _super);

    function App() {
      this.models = {};
    }

    App.prototype.register = function(name, sb) {
      this.models[name] = sb;
      return this;
    };

    App.prototype.createStream = function() {
      var mx, name, sb, sbStream, _ref;
      mx = muxy();
      _ref = this.models;
      for (name in _ref) {
        sb = _ref[name];
        sbStream = sb.createStream();
        sbStream.pipe(mx.open(name)).pipe(sbStream);
      }
      return mx;
    };

    return App;

  })(EventEmitter);

}).call(this);
