// Generated by CoffeeScript 1.6.3
(function() {
  var App, app, ldata, message, messages, muxy, name, through, val;

  through = require('through');

  ldata = require('../shared/live-data');

  muxy = require('muxy');

  App = require('../shared/app');

  exports.client = (typeof window !== "undefined" && window !== null) && (typeof document !== "undefined" && document !== null);

  app = new App;

  exports.app = app;

  val = new ldata.Value;

  val.on('update', function(val) {
    return console.log('val updated, new value:', val);
  });

  app.register('val', val);

  exports.val = val;

  exports.name = name = new ldata.Value;

  name.on('update', function(val) {
    return console.log('name updated, new value:', val);
  });

  app.register('name', name);

  if (exports.client) {
    exports.message = message = new ldata.Value;
  } else {
    exports.message = message = name.map(function(name) {
      return "Hello, " + name + "!";
    });
  }

  app.register('message', message);

  exports.messages = messages = new ldata.Array;

  app.register('messages', messages);

  exports.createStream = function() {
    return app.createStream();
  };

}).call(this);
