// Generated by CoffeeScript 1.6.3
(function() {
  var App, app, greetings, ldata, message, messages, muxy, name, names, through, val;

  through = require('through');

  ldata = require('live-data');

  muxy = require('muxy');

  App = require('../shared/app');

  exports.client = (typeof window !== "undefined" && window !== null) && (typeof document !== "undefined" && document !== null);

  app = new App;

  exports.app = app;

  val = new ldata.Value;

  app.register('val', val);

  exports.val = val;

  exports.name = name = new ldata.Value;

  app.register('name', name);

  if (exports.client) {
    exports.message = message = new ldata.Value;
  } else {
    exports.message = message = name.map(function(name) {
      return "Hello, " + (name || '') + "!";
    });
  }

  app.register('message', message);

  exports.messages = messages = new ldata.Array;

  app.register('messages', messages);

  exports.names = names = new ldata.Array;

  app.register('names', names);

  exports.greetings = greetings = exports.client ? new ldata.Array : names.map(function(name) {
    return "Hello, " + name + "!";
  });

  app.register('greetings', greetings);

  exports.createStream = function() {
    return app.createStream();
  };

}).call(this);
