// Generated by CoffeeScript 1.6.3
(function() {
  var base, fs, ldata, net, reconnect;

  reconnect = require('reconnect');

  ldata = require('live-data');

  base = require('../shared/base');

  net = require('net');

  fs = require('fs');

  reconnect(function(stream) {
    var filter, m;
    stream.pipe(base.createStream()).pipe(stream);
    m = base.messages;
    filter = function(key, raw) {
      var match, parts;
      parts = raw.split(':');
      if (parts.length <= 1 || parts.length > 2 || parts[0].length > 25 || parts[1].length <= 1 || parts[1].length > 75) {
        process.nextTick(function() {
          return m._unset(key);
        });
        return;
      }
      if ((match = /^[^?!.]+([?!.]+)$/.exec(parts[0])) && (match[1].replace(/[^?]/g, '').length > 1 || match[1].replace(/[^!]/g, '').length > 1 || match[1].replace(/[^.]/g, '').length > 1)) {
        return process.nextTick(function() {
          return m._unset(key);
        });
      }
    };
    return m.on('insert', function(index, msg, key) {
      filter(key, msg.get());
      return msg.on('update', filter.bind(this, key));
    });
  }).connect(3010, '127.0.0.1');

}).call(this);
