// Generated by CoffeeScript 1.6.3
(function() {
  var base, ldata, r, reconnect, repl;

  reconnect = require('reconnect');

  ldata = require('live-data');

  repl = require('repl');

  base = require('../shared/base');

  reconnect(function(stream) {
    return stream.pipe(base.createStream()).pipe(stream);
  }).connect(3010);

  r = repl.start({
    useGlobal: true
  });

  r.context.ldata = ldata;

  r.context.base = base;

  r.on('exit', function() {
    return process.exit();
  });

}).call(this);
